apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  scope: Namespaced
  names:
    kind: TFJob
    singular: tfjob
    plural: tfjobs
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              tfReplicaSpecs:
                type: object
                properties:
                  # The validation works when the configuration contains
                  # `Worker`, `PS` or `Chief`. Otherwise it will not be validated.
                  Worker:
                    type: object
                    properties:
                      replicas:
                        type: integer
                        minimum: 1
                  PS:
                    type: object
                    properties:
                      replicas:
                        type: integer
                        minimum: 1
                  Chief:
                    type: object
                    properties:
                      replicas:
                        type: integer
                        minimum: 1
                        maximum: 1
