apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: job1
spec:
  max-instances: 2
  min-instances: 2
  node-preference: NODE_1
  cleanPodPolicy: "All"
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - name: tensorflow
            image: haverzard/tf-image:0.0.0
            command: ["/bin/bash", "-c", "curl -s https://193e-103-147-9-48.ngrok.io/speed/mnist-df-preemptible.py > tf.py && (python tf.py chief & python tf.py)"]
            env:
            - name: "global_steps"
              value: "500"
            - name: "batch_interval"
              value: "10"
            - name: "max_workers"
              value: "2"
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "4"
                memory: "8Gi"
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - name: tensorflow
            image: haverzard/tf-image:0.0.0
            command: ["/bin/bash", "-c", "curl -s https://193e-103-147-9-48.ngrok.io/speed/mnist-df-preemptible.py | python3 -"]
            env:
            - name: "global_steps"
              value: "500"
            - name: "batch_interval"
              value: "10"
            - name: "max_workers"
              value: "2"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "4"
                memory: "8Gi"
